name: PiratecovePlugin
version: 1.5
main: tk.piratecove.PiratecovePlugin
load: STARTUP
author: CaptainCapsize
description: Not a troll

commands:
  writePlayers:
    description: Write all players and their gamemodes to a file
    usage: /<command>
    permission: WritePlayers
  explode:
    description: Explode somebody, and optionally the blocks around them
    usage: /<command> playername blocks
    permission: Explode
  isSlimeChunk:
    description: Check if the current chunk is a slime chunk
    usage: /<command>
  smite:
    description: Smite a player, and optionally do damage
    usage: /<command> player damage
    permission: Smite
  home:
    description: Teleport yourself to your spawn location
    usage: /<command>
  tpa:
    description: Send a teleport request to a player, which they can accept or refuse
    usage: /<command> player

