name: getServerInfo
version: 1.1
main: tk.piratecove.getServerInfo.getServerInfo
load: STARTUP
description: Grabs some server info and writes it to a file (to be used on a website)
author: CaptainCapsize

commands:
  writePlayers:
    description: Write all players and their gamemodes to a file
    usage: /<command>
    permission: getServerInfo.writePlayers